### ISSUE TITLE
Request for Role Identity Access Manager to Access All CFE Related Doctypes

### ISSUE THREAD

**Issue by nishith121** [castlecraft/cfe#11]
I would like to propose the implementation of a Role **Identity Access Manager** (IAM)  that would allow for streamlined access to all CFE related doctypes. This enhancement would significantly improve the management of permissions and access control within the application, ensuring that users can efficiently interact with the necessary resources without providing System Manager role access

**Comment by revant** [comment]
available in v2.2.0
